### PR TITLE
Sfe 458 fa ivr

### PR DESCRIPTION
**Pull request by rdavies3**
This adds the refresh to the beginning of the FS Status stored proc.

### CODE REVIEW

**Comment by rdavies3** [comment]
Jonathan, can you review this pull request?  I'd like to see if you see the change, and understand the need for it.

**Comment by jldalbey** [comment]
@rdavies3 Yea, I see the changes. Dropping the files for the User Provisioning out of the branch for our IVR stuff.

**Comment by jldalbey** [comment]
And yes, I understand the usage and need for the SF_Refresh.

**Comment by rdavies3** [comment]
Nope, that didn't work at all.  What was supposed to show was the addition of the sf_refresh step to the FA Status stored procedure.  It looks like it got missed, and I didn't catch it in my review.  It IS in the student account sproc.  

This totally isn't working is it....

**Pull request closed without merging**
